export const CORRECT_GUESS = 'CORRECT_GUESS';
export const GUESS_WORD = 'GUESS_WORD';
export const RESET_CORRECT_GUESS = 'RESET_CORRECT_GUESS';
export const RESET_GUESSED_WORDS = 'RESET_GUESSED_WORDS';
export const SET_SECRET_WORD = 'SET_SECRET_WORD';
